# Site settings
title: MMP240
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the class note for Multimedia Development class, an intro-level Web Development class offered by City University of New York.
baseurl: "/MMP240jekyll"
url: "/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
